### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by par4m** [par4m/nvim#1]
- [x] [which-key.nvim](https://github.com/folke/which-key.nvim) 
- [ ] [vim-illuminate](https://github.com/RRethy/vim-illuminate) 
- [ ] [vim-fugitive](https://github.com/tpope/vim-fugitive)
- [ ] [vim-repeat](https://github.com/tpope/vim-repeat)
- [x] [vim-surround](https://github.com/tpope/vim-surround)
- [x] [vim-unimpaired](github.com/tpope/vim-unimpaired)
- [x] [trouble.nvim](https://github.com/folke/trouble.nvim)
- [x] [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim)
- [x] [tami5/lspsaga.nvim](https://github.com/tami5/lspsaga.nvim)
- [ ] [navigator.lua](https://github.com/ray-x/navigator.lua)
- [x] [harpoon](https://github.com/ThePrimeagen/harpoon)
- [ ] [marks.nvim](https://github.com/chentoast/marks.nvim)
- [ ] [alpha-nvim](https://github.com/goolord/alpha-nvim)
- [ ] [project.nvim](https://github.com/ahmedkhalf/project.nvim)
- [x] [symbols-outline.nvim](https://github.com/simrat39/symbols-outline.nvim)
- [ ] [specs.nvim](https://github.com/edluffy/specs.nvim)
- [ ] [cmp-rg](https://github.com/lukas-reineke/cmp-rg)
- [ ] [cmp-nvim-lsp-document-symbol](https://github.com/hrsh7th/cmp-nvim-lsp-document-symbol)
- [x] [duck.nvim](https://github.com/tamton-aquib/duck.nvim)
- [ ] [neogen](https://github.com/danymat/neogen)
- [ ] [cheatsheet.nvim](https://github.com/sudormrfbin/cheatsheet.nvim)
- [x] [sniprun](https://github.com/michaelb/sniprun)
- [x] [nvim-ts-autotag](https://github.com/windwp/nvim-ts-autotag)
- [x] [Shade.nvim](https://github.com/sunjon/Shade.nvim)
- [x] [lightspeed.nvim](https://github.com/ggandor/lightspeed.nvim)
- [ ] [toggletasks.nvim](github.com/jedrzejboczar/toggletasks.nvim)
- [ ] [competitest.nvim](https://github.com/xeluxee/competitest.nvim)
- [ ] [cphelper.nvim](https://github.com/p00f/cphelper.nvim)
- [ ] [neogit](https://github.com/TimUntersberger/neogit)
- [ ] [lazygit](https://github.com/kdheepak/lazygit.nvim)
- [ ] [glow.nvim](https://github.com/ellisonleao/glow.nvim)
- [x] [markdown-preview.nvim](https://github.com/iamcco/markdown-preview.nvim)
- [ ] [AutoSave.nvim](https://github.com/Pocco81/AutoSave.nvim)
- [ ] [bracey.vim](https://github.com/turbio/bracey.vim)
- [ ] [gh.nvim](https://github.com/ldelossa/gh.nvim)
- [ ] [key-menu.nvim](https://github.com/linty-org/key-menu.nvim)
- [ ] [zk-nvim](https://github.com/mickael-menu/zk-nvim)
- [ ] [cybu.nvim](https://github.com/ghillb/cybu.nvim)
- [ ] [nvim-docs-view](https://github.com/amrbashir/nvim-docs-view)
- [ ] [readline.nvim](https://github.com/linty-org/readline.nvim)
- [ ] [windex.nvim](https://github.com/declancm/windex.nvim)
- [x] [nvim-spectre](https://github.com/nvim-pack/nvim-spectre)
- [x] [nvim-dap](https://github.com/mfussenegger/nvim-dap)
- [x] [nvim-dap-python](https://github.com/mfussenegger/nvim-dap-python)
- [ ] Add winbar [ChristianChiarulli/winbar.lua](https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/winbar.lua) or use just winbar from [feline.nvim](https://github.com/feline-nvim/feline.nvim) if possible ~~or [incline.nvim](https://github.com/b0o/incline.nvim) when [winbar is integrated](https://github.com/b0o/incline.nvim/issues/19)~~
- [ ] Add [nvim-gps](https://github.com/SmiteshP/nvim-gps) when https://github.com/SmiteshP/nvim-gps/issues/103 is added
- [x] Replace [neoscroll](https://github.com/karb94/neoscroll.nvim) with ~~[cinnamon.nvim](https://github.com/declancm/cinnamon.nvim)~~ or [vim-smoothie](https://github.com/psliwka/vim-smoothie)
- [ ] Add [vim-abolish](https://github.com/tpope/vim-abolish)  when [inccommand preview](https://github.com/tpope/vim-abolish/issues/107) is added
- [ ] Add [cder.nvim](https://github.com/Zane-/cder.nvim)

**Comment by par4m** [comment]
Replace [neoscroll](https://github.com/karb94/neoscroll.nvim) with [cinnamon.nvim](https://github.com/declancm/cinnamon.nvim) ?

**Comment by par4m** [comment]
Replace manual lsp config with [nvim-lsp-setup]https://github.com/Junnplus/nvim-lsp-setup ?

**Comment by par4m** [comment]
Add [nvim-gps](https://github.com/SmiteshP/nvim-gps) when https://github.com/SmiteshP/nvim-gps/issues/103 is added

**Comment by par4m** [comment]
Add winbar 
[ChristianChiarulli/winbar.lua](https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/winbar.lua) or use just winbar from [feline.nvim](https://github.com/feline-nvim/feline.nvim) if possible
